version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
test: off
artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/widec/api/v2/package
  api_key:
    secure: BADYsTqKarKemQHDOKWHXzGJOBONzp6uIlZSW5kHXtEWs1l56tWTRGRKQddUrENz
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: uswUtBM1in8EX//QnTpszmlAkkhMYtpeQ9EMiGqu1tTAejMkG0hXdUlnLP5yvhjr
  on:
    branch: master
    appveyor_repo_tag: true
